Repository AY2425S1-CS2103-F10-3/tp, pull requests merged in 2024-11, with the labels that each got.

#255 Implement undo feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/bizbook/logic/LogicManager.java
  src/main/java/bizbook/logic/commands/PinCommand.java
  src/main/java/bizbook/logic/commands/UndoCommand.java
  src/main/java/bizbook/logic/commands/UnpinCommand.java
  src/main/java/bizbook/logic/parser/AddressBookParser.java
  src/main/java/bizbook/model/AddressBook.java
  src/main/java/bizbook/model/Model.java
  src/main/java/bizbook/model/ModelManager.java
  src/main/java/bizbook/model/ReadOnlyAddressBook.java
  src/main/java/bizbook/model/VersionedAddressBook.java
  src/test/java/bizbook/logic/commands/AddCommandTest.java
  src/test/java/bizbook/logic/commands/ExportCommandTest.java
  src/test/java/bizbook/logic/commands/PinCommandTest.java
  src/test/java/bizbook/logic/commands/UndoCommandTest.java
  src/test/java/bizbook/logic/commands/UnpinCommandTest.java
  src/test/java/bizbook/logic/parser/AddressBookParserTest.java
  src/test/java/bizbook/logic/parser/EditNotesCommandParserTest.java
  src/test/java/bizbook/model/AddressBookTest.java
Labels: priority.Medium, type.Task

#252 Fix VCFExporter to write structured name and only write categories if needed
  src/main/java/bizbook/logic/commands/exporter/VcfExporter.java
  src/test/java/bizbook/logic/commands/exporter/VcfExporterTest.java
  src/test/resources/logic/commands/exporter/VcfExporterTest/charlie.vcf
  src/test/resources/logic/commands/exporter/VcfExporterTest/people.vcf
Labels: severity.Low, type.Bug, alpha-bug

#249 Add unit tests for delete notes and add notes command parser
  src/main/java/bizbook/logic/commands/DeleteNotesCommand.java
  src/test/java/bizbook/logic/commands/DeleteNotesCommandTest.java
  src/test/java/bizbook/logic/parser/AddNotesCommandParserTest.java
  src/test/java/bizbook/logic/parser/DeleteNotesCommandParserTest.java
Labels: priority.High

#242 Fix bug where contact detail panel does not update
  docs/UserGuide.md
  src/main/java/bizbook/logic/commands/ClearCommand.java
  src/main/java/bizbook/logic/commands/DeleteCommand.java
  src/main/java/bizbook/logic/commands/DeleteNotesCommand.java
  src/main/java/bizbook/logic/commands/EditCommand.java
  src/main/java/bizbook/logic/commands/UndoCommand.java
  src/main/java/bizbook/logic/commands/ViewCommand.java
  src/main/java/bizbook/model/Model.java
  src/main/java/bizbook/model/ModelManager.java
  src/main/java/bizbook/ui/ContactDetails.java
  src/test/java/bizbook/logic/commands/AddCommandTest.java
  src/test/java/bizbook/model/ModelManagerTest.java
Labels: priority.High, severity.Medium, alpha-bug

#277 Add delete tag command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/bizbook/logic/commands/DeleteTagCommand.java
  src/main/java/bizbook/logic/parser/AddressBookParser.java
  src/main/java/bizbook/logic/parser/DeleteTagCommandParser.java
  src/test/java/bizbook/logic/commands/CommandTestUtil.java
  src/test/java/bizbook/logic/commands/DeleteTagCommandTest.java
  src/test/java/bizbook/logic/parser/AddressBookParserTest.java
  src/test/java/bizbook/logic/parser/DeleteTagCommandParserTest.java
Labels: priority.Medium

#287 Update storage tests to include notes
  src/main/java/bizbook/storage/JsonAdaptedPerson.java
  src/test/java/bizbook/storage/JsonAdaptedPersonTest.java
Labels: priority.Medium

#286 Bug fix: Add duplicate note check where capital is considered
  src/main/java/bizbook/logic/commands/AddNoteCommand.java
  src/main/java/bizbook/logic/commands/DeleteNoteCommand.java
  src/main/java/bizbook/logic/commands/EditNoteCommand.java
  src/main/java/bizbook/model/person/Note.java
  src/test/java/bizbook/logic/commands/AddNoteCommandTest.java
  src/test/java/bizbook/logic/commands/CommandTestUtil.java
  src/test/java/bizbook/logic/commands/EditNoteCommandTest.java
  src/test/java/bizbook/model/person/NoteTest.java
  src/test/java/bizbook/testutil/TypicalIndexes.java
Labels: priority.High

#291 Fix ContactDetails to have composition from MainWindow
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: severity.Low, type.Bug, alpha-bug

#295 Update ContactDetails to use ScrollPane and wrap text
  src/main/java/bizbook/ui/ContactDetails.java
  src/main/resources/view/ContactDetails.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, alpha-bug

#297 Update Undo/Redo Implementation in DG
  docs/DeveloperGuide.md
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  docs/diagrams/UndoSequenceDiagram-Model.puml
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram-Logic.png
  docs/images/UndoSequenceDiagram-Model.png
  src/main/java/bizbook/ui/ContactDetails.java
Labels: severity.VeryLow, type.Task

#299 Update ui img in README and UG
  docs/images/Ui.png
Labels: priority.High

#292 Update help window with current commands
  src/main/java/bizbook/logic/commands/ClearCommand.java
  src/main/java/bizbook/logic/commands/ExitCommand.java
  src/main/java/bizbook/logic/commands/ListCommand.java
  src/main/java/bizbook/logic/commands/RedoCommand.java
  src/main/java/bizbook/logic/commands/ToggleCommand.java
  src/main/java/bizbook/logic/commands/UndoCommand.java
  src/main/java/bizbook/ui/CommandTablePanel.java
  src/test/java/bizbook/logic/parser/EditCommandParserTest.java
Labels: type.Bug, alpha-bug

#253 Add Import command and support for importing VCF
  src/main/java/bizbook/logic/Messages.java
  src/main/java/bizbook/logic/commands/ExportCommand.java
  src/main/java/bizbook/logic/commands/ImportCommand.java
  src/main/java/bizbook/logic/commands/exporter/CsvExporter.java
  src/main/java/bizbook/logic/commands/exporter/Exporter.java
  src/main/java/bizbook/logic/commands/exporter/FileType.java
  src/main/java/bizbook/logic/commands/exporter/Importer.java
  src/main/java/bizbook/logic/commands/exporter/VcfExporter.java
  src/main/java/bizbook/logic/commands/exporter/VcfImporter.java
  src/main/java/bizbook/logic/commands/exporter/exceptions/EmptyAddressBookException.java
  src/main/java/bizbook/logic/commands/exporter/exceptions/InvalidAddressBookException.java
  src/main/java/bizbook/logic/commands/exporter/exceptions/InvalidFileException.java
  src/main/java/bizbook/logic/parser/AddressBookParser.java
  src/main/java/bizbook/logic/parser/CliSyntax.java
  src/main/java/bizbook/logic/parser/ExportCommandParser.java
  src/main/java/bizbook/logic/parser/ImportCommandParser.java
  src/main/java/bizbook/logic/parser/ParserUtil.java
  src/test/java/bizbook/logic/commands/ExportCommandTest.java
  src/test/java/bizbook/logic/commands/ImportCommandTest.java
  src/test/java/bizbook/logic/commands/exporter/CsvExporterTest.java
  src/test/java/bizbook/logic/commands/exporter/VcfExporterTest.java
  src/test/java/bizbook/logic/commands/exporter/VcfImporterTest.java
  src/test/java/bizbook/logic/parser/ExportCommandParserTest.java
  src/test/java/bizbook/logic/parser/ImportCommandParserTest.java
  src/test/java/bizbook/testutil/TestUtil.java
  src/test/resources/bizbook/logic/commands/ImportCommandTest/invalid_info.vcf
  src/test/resources/bizbook/logic/commands/ImportCommandTest/typical.vcf
  src/test/resources/bizbook/logic/commands/exporter/CsvExporterTest/charlie.csv
  src/test/resources/bizbook/logic/commands/exporter/CsvExporterTest/people.csv
  src/test/resources/bizbook/logic/commands/exporter/VcfExporterTest/charlie.vcf
  src/test/resources/bizbook/logic/commands/exporter/VcfExporterTest/people.vcf
  src/test/resources/bizbook/logic/commands/exporter/VcfImporterTest/empty.vcf
  src/test/resources/bizbook/logic/commands/exporter/VcfImporterTest/invalid_info.vcf
  src/test/resources/bizbook/logic/commands/exporter/VcfImporterTest/missing_info.vcf
  src/test/resources/bizbook/logic/commands/exporter/VcfImporterTest/single.vcf
  src/test/resources/bizbook/logic/commands/exporter/VcfImporterTest/typical.vcf
  src/test/resources/bizbook/logic/commands/exporter/VcfImporterTest/wrong_format.vcf
Labels: priority.Medium, type.Enhancement

#302 Remove table of content
  docs/DeveloperGuide.md
Labels: priority.High

#307 Update jar file name
  docs/UserGuide.md
Labels: priority.High

#316 Update index.md and User Guide
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/index.md
  src/main/java/bizbook/logic/commands/DeleteTagCommand.java
Labels: type.Task

#317 Update ImportCommand to clear focused person after execution
  src/main/java/bizbook/logic/commands/ImportCommand.java
Labels: type.Bug, alpha-bug

#369 Fix several dg ug pe bugs
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
Labels: due.Sunday

#371 Update diagrams and description in DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
Labels: due.Sunday, type.documentation-bug

#374 Add table of contents in UG
  docs/UserGuide.md
Labels: due.Sunday, type.documentation-bug

#373 Add table of contents to DG
  docs/DeveloperGuide.md
Labels: due.Sunday, type.documentation-bug

#376 Remove fullstop in add note command example
  src/main/java/bizbook/logic/commands/AddNoteCommand.java
Labels: type.Bug, due.Sunday

#379 Update config file to correctly link to BB repo instead of AB3 and fix UI CD width
  docs/DeveloperGuide.md
  docs/_config.yml
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: due.Sunday

#377 Update UG to clarify email and notes validation
  docs/UserGuide.md
Labels: due.Sunday

#385 Update contact us in AboutUs.md
  docs/AboutUs.md
Labels: type.documentation-bug

#389 Update indenting for TOC in UG
  docs/UserGuide.md
Labels: due.Monday, type.documentation-bug

#388 Update indenting for TOC in DG
  docs/DeveloperGuide.md
Labels: due.Monday, type.documentation-bug

#380 Add visuals in UG
  docs/UserGuide.md
  docs/images/BeforeUnpin.png
  docs/images/PinCommandResult.png
  docs/images/UiInDarkMode.png
  docs/images/UiInLightMode.png
  docs/images/UnpinCommandResult.png
  docs/images/ViewCommandResult.png
Labels: due.Sunday, type.documentation-bug

#382 Update answer to transfer data question in UG
  docs/UserGuide.md
Labels: due.Sunday

#403 Fix broken links in TOC
  docs/UserGuide.md
Labels: type.documentation-bug
