Repository AY2425S1-CS2103-F10-3/tp, pull requests merged in 2024-10, with the labels that each got.

#179 Update shadowJar name to bizbook
  build.gradle
Labels: severity.VeryLow

#189 Update model and storage CDs to include note
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: priority.High

#219 Fix ContactDetails inside UiClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Bug
